### ISSUE TITLE
Create a user model

### ISSUE THREAD

**Issue by PixDay** [PixDay/Tool-Mania#13]
First step define with @PixDay the User model
Minimum: 
- [ ] Firstname
- [ ] Lastname
- [ ] Email
- [ ] Password
- [ ] id

Create a model folder and create an exportable User interface

**Comment by SlavicPavlovic** [comment]
I would like to possibly add the phone number to the user model directly. On the "follow your order" page we could do some interesting stuff with it (see: https://tool-mania.com/apps/trackorder)

**Comment by SlavicPavlovic** [comment]
As seen during the call, we will also be adding the necessary fields to the user directly so that we can define an address: Street Number, Street Name, Postal Code, City Name, Country, and additional info field.

**Comment by PixDay** [comment]
Can you just make the street number and street name a single string field please make sense in France for adresses like: 
`2 bis, Rue Royale`

**Comment by SlavicPavlovic** [comment]
For the precision sake, here is what the semi-final form of the model looks right now, with the last updates possibly made during the eventual merge request:

1. First Name
2. Last Name
3. Email
4. Password
5. id (auto-generated)
6. Street Number & Name field
7. Postal Code
8. City Name
9. Country

**Comment by PixDay** [comment]
LGTM :+1:

**Comment by PixDay** [comment]
A new field for the User: `role` to determine if the user is just a customer or an admin of the web application 
it will be a simple string for you and will only take 2 possible values:
- 'admin'
- 'customer'

**Comment by SlavicPavlovic** [comment]
I would like to propose a boolean for that, it's easier to work with for you guys in the front as well nah? Admin: true/false
