### ISSUE TITLE
Create a Product model

### ISSUE THREAD

**Issue by PixDay** [PixDay/Tool-Mania#17]
With @PixDay create an exportable Inteface for product

Must at least contain:

- [ ] id
- [ ] Title
- [ ] description
- [ ] image (src path)
- [ ] price
- [ ] promo

**Comment by PixDay** [comment]
As I see in their website a product can have multiple images...
We will create an array of images that correspond to the paths of the images

**Comment by SlavicPavlovic** [comment]
As seen on their website, there should also be a field (possibly a boolean, can evolve afterwards) if the product is insured or not by the company.

**Comment by SlavicPavlovic** [comment]
[images]
title
price
sale level % (0-100)
product type
product description
{options}
{fields}

I think that with this we are mostly ok, as seen during our call.

**Comment by PixDay** [comment]
Yes let's start with that and I will have a call with him tonight to confirm or if we will update the interface
